// <auto-generated />
namespace anipet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class with_newcontrollersandviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(with_newcontrollersandviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201908101159500_with_newcontrollersandviews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
